---
language: python
services: docker

env:
  global:
    - ROLE_NAME: k8s_base
  matrix:
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
