---

# fool protection

- name: hold k8s binaries versions
  command: apt-mark hold kubelet kubeadm kubectl
  changed_when: false

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

- name: configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ k8s_base_node_ip }}
    create: true

- name: restart kubelet
  service:
    name: kubelet
    daemon_reload: true
    state: restarted
  when: not ( molecule_test | default('false') )
